### ISSUE TITLE
Creating a working gui

### ISSUE THREAD

**Issue by ghost** [Xonshiz/comic-dl-GUI#1]
So, I'm actually learning self learning ui/ux design. I'm ready to build a gui for comic-dl (your app that i really like) using cefpython. But I'll kinda need you to restructure conic-dl a bit to make the gui manageable. Let me know if your interested.

**Comment by Xonshiz** [comment]
Hey, this is a very very old repo and I have dropped the idea for this.
You could move to "[Comic-dl](https://github.com/Xonshiz/comic-dl)" instead and fork it and make your changes.

Will be closing this one here.

**Comment by ghost** [comment]
Cool
